### ISSUE TITLE
Monitoring multiple accounts simultaneously?

### ISSUE THREAD

**Issue by thecodesmith** [theodore86/github-rate-limits-exporter#354]
Hello, thanks for this project! I am successfully using it to monitor the rate limit for a user account, however I have a number of GitHub Apps that I would also like to monitor. To monitor multiple apps will I need to install multiple copies of Helm chart with the app details for each? Or is there a way to monitor multiple apps with a single deployment? Thanks!

**Comment by theodore86** [comment]
Hey @thecodesmith thanks for your nice proposal, the easiest way to achive this is to have multiple **values-*.yml** per account and use the helm package manager or any other deployment tool such as [helmfile ](https://github.com/roboll/helmfile) to deploy multiple instances of the exporter, in reality you can think of each exporter as a single process inside OS, moreover you could easily monitor/observe your accounts via Grafana/Prometheus

**Comment by thecodesmith** [comment]
Sounds good, I will go that route. Thanks again!
